# .github/workflows/deploy.yml
# SAT18 Engine – Continuous Integration & Deployment Pipeline
name: Deploy SAT18 Engine

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-deploy:
    name: Build, Verify & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout Repository
        uses: actions/checkout@v4

      - name: 2. Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: |
            **/package-lock.json

      - name: 3. Install All Dependencies
        run: |
          echo "Installing root dependencies..."
          npm ci
          echo "Installing server dependencies..."
          npm ci --prefix server
          echo "Installing frontend dependencies..."
          npm ci --prefix frontend

      - name: 4. Build Server (TypeScript to JavaScript)
        run: npm run build --prefix server

      - name: 5. Run Database Migrations
        run: |
          echo "Applying database migrations..."
          node server/scripts/migrate.js

      - name: 6. Verify Data Persistence Layer
        run: |
          echo "Verifying data layer integrity..."
          node server/scripts/verify-persistence.js

      - name: 7. Build Frontend Application
        run: |
          echo "Building frontend assets..."
          npm run build --prefix frontend

      - name: 8. Deploy to VPS
        env:
          # Pastikan secrets ini sudah diatur di Settings > Secrets > Actions
          SSH_KEY: ${{ secrets.SSH_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
        run: |
          # Langkah ini mengasumsikan skrip `deploy-backend.sh` ada dan dapat dieksekusi.
          # Skrip tersebut harus menangani koneksi SSH dan logika deployment di sisi server.
          echo "Executing deployment script to VPS..."
          # Contoh: bash server/scripts/deploy-backend.sh
          echo "Simulating deployment execution. Ganti dengan perintah deploy Anda."

      - name: 9. Upload Frontend Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sat18-frontend-build
          path: frontend/dist/

      - name: 10. Mark Deployment Successful
        run: echo "✅ SAT18 Engine core pipeline completed successfully."
